---
version: '3.8'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    container_name: hub
  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 5901:5900
    links:
      - hub:selenium
    container_name: chrome    
  firefox:
    image: selenium/standalone-firefox-debug
    ports:
      - 5902:5900
    links:
      - hub:selenium
    container_name: firefox    
...

