---
version: '3.8'
services:
  myjenkins:
    image: jenkins/jenkins
    ports:
      - 8081:8080
    networks:
      - abc
  qaservre:
    image: tomee
    ports:
      - 8082:8080
    networks:
      - xyz
  prodserver:
    image: tomee
    ports:
      - 8083:8080
    networks:
      - xyz

networks:
  abc: {}
  xyz: {}
        
