---
version: '3,8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - db:/var/lib/mysql    
  myword:
    image: wordpress
    ports:
      - 8080:80
    volumes:
      - word:/var/ww/html    
volumes:
  db:
  word:  
