---
version: '3.8'
services:
  mydb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
  
  mywordpress:
    image: wordpress
    ports:
     - 8080:80
    links:
     - mydb:mysql
...       
